apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: notes-server-hpa 
  namespace: notes-app

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
